### ISSUE TITLE
変数

### ISSUE THREAD

**Issue by c0b210665f** [EbataAsunari/ProjExD_pub#5]
https://github.com/EbataAsunari/ProjExD_pub/blob/978ca2226e38ad5274889295f1202f2dd3dcb618/dodge_bomb.py#L153
変数の値をコードに関連する名前にした方が、あとから見た時にわかりやすいと思います

**Comment by Andr0medapants** [comment]
変数の値の名前はrandomの頭文字を意味するrに設定してあるので、コードに関連する名前になっていると考えています
