### ISSUE TITLE
スコア方法

### ISSUE THREAD

**Issue by c0b21140f1** [EbataAsunari/ProjExD_pub#8]
https://github.com/EbataAsunari/ProjExD_pub/blob/978ca2226e38ad5274889295f1202f2dd3dcb618/dodge_bomb.py#L80
スコアがプラスになる基準が時間だとスコアが大きくなりすぎてしまうので他の方法が良いと思いました。
C0B21140_堀江泰綺

**Comment by TakumaFunatogawa** [comment]
修正しました。
